### 다른 모델 가져다 써보기

In [1]:
pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 81.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.4/182.4 KB 24.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 105.7 MB/s eta 0:00:00


In [2]:
from transformers import AutoTokenizer

In [3]:
model = "matthewburke/korean_sentiment"

In [4]:
tokenizer=AutoTokenizer.from_pretrained(model)

Downloading:   0%|          | 0.00/552 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/396k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/788k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [5]:
raw_inputs = [
    "너희들은 안늙었구나..",
    "언론이 왜이렇게 과하게 밀어주는거지? 일본 머니가 힘이 좋기는 좋구나...",
    "기억상실증에 걸렸으면 좋겠다. 다시 보고 다시보고 다시보고 싶다."
]

In [7]:
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="pt") #pt = pytorch

In [8]:
inputs

{'input_ids': tensor([[    2, 13283,  2434,  5114, 14750,    18,    18,     3,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    2, 10760, 15620, 38874,  4131, 44751,  8370,    33,  7998, 22369,
          4050, 11370,  2895,  8194,  2895,  8037,    18,    18,    18,     3],
        [    2,  9070,  4156,  4510,  4193,  4063, 12789,  7991,  9000,    18,
          8244,  8200,  8244,  8201,  8244,  8201,  8984,    18,     3,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]])}

In [9]:
from transformers import AutoModel

In [10]:
pre_model=AutoModel.from_pretrained(model)

Downloading:   0%|          | 0.00/887 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/498M [00:00<?, ?B/s]

Some weights of the model checkpoint at matthewburke/korean_sentiment were not used when initializing ElectraModel: ['classifier.dense.weight', 'classifier.out_proj.weight', 'classifier.dense.bias', 'classifier.out_proj.bias']
- This IS expected if you are initializing ElectraModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ElectraModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [11]:
outputs=pre_model(**inputs)

In [13]:
outputs.last_hidden_state.shape # input의 갯수, 문장당 token의 max-갯수, token당 출력하는 배열의 갯수

torch.Size([3, 20, 768])

In [17]:
from transformers import AutoModelForSequenceClassification

In [22]:
clf = AutoModelForSequenceClassification.from_pretrained(model)

In [23]:
outputs2 = clf(**inputs)

In [26]:
outputs2.logits # 1,2,3문장에 대한 결괏값 (softmax 들어가기 전 값)

tensor([[-3.9915e-02,  1.4292e-03],
        [ 1.3187e+00, -1.2230e+00],
        [-1.5856e+00,  1.3957e+00]], grad_fn=<AddmmBackward0>)

In [27]:
import torch

In [29]:
prediction = torch.nn.functional.softmax(outputs2.logits, dim=-1)

In [30]:
prediction

tensor([[0.4897, 0.5103],
        [0.9270, 0.0730],
        [0.0483, 0.9517]], grad_fn=<SoftmaxBackward0>)

In [31]:
clf.config.id2label

{0: 'LABEL_0', 1: 'LABEL_1'}

In [32]:
raw_inputs

['너희들은 안늙었구나..',
 '언론이 왜이렇게 과하게 밀어주는거지? 일본 머니가 힘이 좋기는 좋구나...',
 '기억상실증에 걸렸으면 좋겠다. 다시 보고 다시보고 다시보고 싶다.']

------------

In [33]:
model = "beomi/korean-hatespeech-multilabel"

In [34]:
tokenizer=AutoTokenizer.from_pretrained(model)

Downloading:   0%|          | 0.00/584 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/396k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/788k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [35]:
raw_inputs = [
    "너희들은 안늙었구나..",
    "언론이 왜이렇게 과하게 밀어주는거지? 일본 머니가 힘이 좋기는 좋구나...",
    "기억상실증에 걸렸으면 좋겠다. 다시 보고 다시보고 다시보고 싶다."
]

In [36]:
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="pt") #pt = pytorch

In [37]:
inputs

{'input_ids': tensor([[    2, 13283,  2434,  5114, 14750,    18,    18,     3,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    2, 10760, 15620, 38874,  4131, 44751,  8370,    33,  7998, 22369,
          4050, 11370,  2895,  8194,  2895,  8037,    18,    18,    18,     3],
        [    2,  9070,  4156,  4510,  4193,  4063, 12789,  7991,  9000,    18,
          8244,  8200,  8244,  8201,  8244,  8201,  8984,    18,     3,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]])}

In [38]:
pre_model=AutoModel.from_pretrained(model)

Downloading:   0%|          | 0.00/1.07k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/498M [00:00<?, ?B/s]

Some weights of the model checkpoint at beomi/korean-hatespeech-multilabel were not used when initializing ElectraModel: ['classifier.dense.weight', 'classifier.out_proj.weight', 'classifier.dense.bias', 'classifier.out_proj.bias']
- This IS expected if you are initializing ElectraModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ElectraModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [39]:
outputs=pre_model(**inputs)

In [40]:
outputs.last_hidden_state.shape # input의 갯수, 문장당 token의 max-갯수, token당 출력하는 배열의 갯수

torch.Size([3, 20, 768])

In [41]:
clf = AutoModelForSequenceClassification.from_pretrained(model)

In [42]:
outputs2 = clf(**inputs)

In [43]:
outputs2.logits # 1,2,3문장에 대한 결괏값 (softmax 들어가기 전 값)

tensor([[ 0.0716, -3.8322,  1.5945, -2.3130],
        [ 0.1339, -4.5619,  0.6361, -2.0854],
        [-4.1502, -4.1497, -2.8878, -3.9213]], grad_fn=<AddmmBackward0>)

In [44]:
prediction = torch.nn.functional.softmax(outputs2.logits, dim=-1)

In [45]:
prediction

tensor([[0.1755, 0.0035, 0.8048, 0.0162],
        [0.3610, 0.0033, 0.5965, 0.0392],
        [0.1472, 0.1473, 0.5203, 0.1851]], grad_fn=<SoftmaxBackward0>)