In [4]:
import numpy as np

# Numpy 연산

In [6]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,1],[1,6]])

In [7]:
A+B

array([[ 4,  3],
       [ 4, 10]])

In [8]:
A*B

array([[ 3,  2],
       [ 3, 24]])

In [9]:
A

array([[1, 2],
       [3, 4]])

In [10]:
B

array([[3, 1],
       [1, 6]])

In [11]:
C = 10

In [13]:
A + C ## Broadcast


array([[11, 12],
       [13, 14]])

In [14]:
D = np.array([10,20])

In [15]:
A+D

array([[11, 22],
       [13, 24]])

In [17]:
A

array([[1, 2],
       [3, 4]])

In [18]:
B

array([[3, 1],
       [1, 6]])

In [19]:
np.dot(A,B)

array([[ 5, 13],
       [13, 27]])

In [20]:
np.dot(A,C)

array([[10, 20],
       [30, 40]])

In [21]:
np.dot(A,D)

array([ 50, 110])

In [27]:
E = np.array([[2],[4],[6]])

In [32]:
E # 3행 1열 (3,1)  "1 x 3"

array([[2],
       [4],
       [6]])

In [29]:
A

array([[1, 2],
       [3, 4]])

In [31]:
np.dot(E,A) # 행렬이 안맞아서 내적 불가

ValueError: shapes (3,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)