# Neural Network 인공신경망

In [1]:
import numpy as np

In [4]:
X = np.array([1,2])
W = np.array([[1,3,5],[2,4,6]])
B = np.array([1,1,1])

In [5]:
Y = np.dot(X,W) + B

In [6]:
print(Y)

[ 6 12 18]


In [7]:
# A1 = X1 * W1 + B1

X1 = np.array([1.,.5])
B1 = np.array([.1,.2,.3])
W1 = np.array([[.1,.3,.5],[.2,.4,.6]])

In [8]:
A1 = np.dot(X1,W1) + B1

In [9]:
print(A1)

[0.3 0.7 1.1]


----

### 1층

In [11]:
def sigmoid(x):
    return 1 / (1+ np.exp(-x))

In [14]:
Z1= sigmoid(A1)

In [15]:
Z1

array([0.57444252, 0.66818777, 0.75026011])

-----

### 2층

In [16]:
# A2 = Z1 * W2 + B2

W2 = np.array([[.1,.4],[.2,.5],[.3,.6]])
B2 = np.array([.1,.2])

In [17]:
A2 = np.dot(Z1, W2) + B2

In [18]:
print(A2)

[0.51615984 1.21402696]


In [20]:
Z2 = sigmoid(A2)

In [21]:
print(Z2)

[0.62624937 0.7710107 ]


-----

### 3층

In [26]:
# A3 = Z2 * W3 + B3

W3 = np.array([[.1,.3],[.2,.4]])
B3 = np.array([.1,.2])

A3 = np.dot(Z2, W3)+B3

In [28]:
print(A3)

[0.31682708 0.69627909]


In [29]:
#항등 함수
def identity_function(x) :
    return x

In [30]:
Y = identity_function(A3)

In [31]:
Y

array([0.31682708, 0.69627909])

## 전체 코드

In [33]:
#전체코드 구현에 필요한 것들 ; x값 노드마다 w값 b값 sigmoid함수 , identify함수

In [37]:
def sigmoid(x):
    return 1 / (1+ np.exp(-x))

In [38]:
#항등 함수
def identity_function(x) :
    return x

In [39]:
def init_network():
    network = {}
    
    network['W1'] = np.array([[.1,.3,.5],[.2,.4,.6]])
    network['B1'] = np.array([.1,.2,.3])
    
    network['W2'] = np.array([[.1,.4],[.2,.5],[.3,.6]])
    network['B2'] = np.array([.1,.2])
        
    network['W3'] = np.array([[.1,.3],[.2,.4]])
    network['B3'] = np.array([.1,.2])
    
    return network

In [41]:
def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['B1'], network['B2'], network['B3']
    
    a1 = np.dot(x,W1) + b1
    z1 = sigmoid(a1)
    
    a2 = np.dot(z1,W2) + b2
    z2 = sigmoid(a2)
    
    a3 = np.dot(z2,W3) + b3
    y = identity_function(a3)
    
    return y

In [42]:
network = init_network()

In [44]:
x = np.array([1.,.5])
y = forward(network, x)


In [45]:
y

array([0.31682708, 0.69627909])

### 소프트맥스 함수

In [46]:
a = np.array([.3, 2.9, 4.])

In [47]:
def softmax(a) :
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a 
    
    return y

In [48]:
softmax(a)

array([0.01821127, 0.24519181, 0.73659691])

In [49]:
np.sum(softmax(a))

1.0

In [54]:
a = np.array([1010,1000,990])
softmax(a)

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [55]:
def softmax(a) :
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a 
    
    return y

In [56]:
a = np.array([1010,1000,990])
softmax(a)
np.sum(softmax(a))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])