In [7]:
class MulLayer :
    def __init__(self) :
        self.x = None
        self.y = None

    def forward(self,x,y) :
        self.x = x
        self.y = y
        out = x * y
        
        return out

    def backward(self, dout):
        dx = dout * self.y
        dy = dout * self.x

        return dx, dy


In [31]:
class AddLayer :
    def __init__(self):
        pass
    
    def forward(self,x,y) :

        return x + y
    
    def backward(self,dout) :
        
        return dout


In [8]:
apple  = 100
apple_num = 2
tax = 1.1

In [9]:
mul_apple_layer = MulLayer()
mul_tax_layer= MulLayer()

In [14]:
apple_price = mul_apple_layer.forward(apple, apple_num)

In [16]:
price = mul_tax_layer.forward(apple_price, tax)

In [17]:
price

220.00000000000003

In [18]:
dprice  = 1

In [20]:
dapple_price= mul_tax_layer.backward(dprice)[0]
dtax = mul_tax_layer.backward(dprice)[1]

In [21]:
dapple_price

1.1

In [22]:
dtax

200

In [23]:
mul_apple_layer.backward(dapple_price)

(2.2, 110.00000000000001)

In [24]:
dapple = mul_apple_layer.backward(dapple_price)[0]

In [25]:
dapple_num = mul_apple_layer.backward(dapple_price)[1]

In [27]:
print(dapple)
print(dapple_num)
print(dapple_price)
print(dtax)

2.2
110.00000000000001
1.1
200


In [28]:
apple , apple_num , orange, orange_num, tax = 100, 2, 150, 3, 1.1

In [32]:
mul_apple_layer = MulLayer()
mul_orange_layer = MulLayer()
add_apple_orange_layer = AddLayer()
total_tax_layer = MulLayer()

In [35]:
mul_apple_price=mul_apple_layer.forward(apple, apple_num)

In [36]:
mul_orange_price = mul_orange_layer.forward(orange, orange_num)

In [38]:
total_apple_orange = add_apple_orange_layer.forward(mul_apple_price,mul_orange_price)

In [40]:
total = total_tax_layer.forward(total_apple_orange, tax)

In [48]:
print(mul_apple_price, mul_orange_price, total_apple_orange, total)

200 450 650 715.0000000000001


---

In [52]:
dprice = 1

In [53]:
dtotal_apple_orange, dtax  = total_tax_layer.backward(dprice)

In [54]:
print(dtotal_apple_orange, dtax)

1.1 650


In [55]:
add_apple_orange_layer.backward(dtotal_apple_orange)

1.1

In [57]:
dapple, dapple_num = mul_apple_layer.backward(dtotal_apple_orange)

In [59]:
dorange, dorange_num = mul_orange_layer.backward(dtotal_apple_orange)

In [60]:
print(dapple, dapple_num, dorange, dorange_num, dtax)

2.2 110.00000000000001 3.3000000000000003 165.0 650


-----

In [61]:
import numpy as np

In [68]:
x = np.array([[1.0,-0.5],[-2.0,3.0]])

In [69]:
x <= 0

array([[False,  True],
       [ True, False]])

In [75]:
class Relu :
    def __init__(self) :
        self.mask = None


    def forward(self,x) :
        self.mask = (x <= 0)
        out = x.copy()
        out[self.mask] = 0

        return out

    def backward(self, dout) :
        dout[self.mask]= 0
        dx = dout

        return dx

In [71]:
relu = Relu()

In [72]:
relu.forward(x)

array([[1., 0.],
       [0., 3.]])

In [73]:
dout = np.array([[1.0,-0.5],[-2.0,3.0]])

In [74]:
relu.backward(dout)

array([[1., 0.],
       [0., 3.]])

--------

In [97]:
X = np.random.rand(2)
W = np.random.rand(2,3)
B = np.random.rand(3)

In [77]:
Y = np.dot(X,W) + B

In [78]:
print(Y)

[0.4074568  0.94707547 0.92004368]


In [80]:
X

array([0.4728981 , 0.31991645])

In [81]:
W

array([[0.04668747, 0.45187141, 0.15777547],
       [0.09051801, 0.07015214, 0.12475531]])

In [82]:
B

array([0.35642019, 0.71094352, 0.80552068])

In [85]:
print(X.shape) # (x,y) x가 열, y가 행
print(W.shape)
print(B.shape)

(2,)
(2, 3)
(3,)


--------

In [86]:
W

array([[0.04668747, 0.45187141, 0.15777547],
       [0.09051801, 0.07015214, 0.12475531]])

In [87]:
W.T

array([[0.04668747, 0.09051801],
       [0.45187141, 0.07015214],
       [0.15777547, 0.12475531]])

In [88]:
np.array(W.T)

array([[0.04668747, 0.09051801],
       [0.45187141, 0.07015214],
       [0.15777547, 0.12475531]])

In [98]:
B

array([0.70675831, 0.77583209, 0.2792807 ])

In [99]:
np.array(B.T)

array([0.70675831, 0.77583209, 0.2792807 ])

In [100]:
np.array([B])

array([[0.70675831, 0.77583209, 0.2792807 ]])

In [101]:
B.shape

(3,)

-------

In [102]:
x_dot_W = np.array([[0,0,0],[10,10,10]]) # 2 x 3
B = np.array([1,2,3]) # 1 x 3

In [108]:
x_dot_W + B #broadcast

array([[ 1,  2,  3],
       [11, 12, 13]])

In [105]:
dy = np.array([[1,2,3],
               [4,5,6]])

In [106]:
db = np.sum(dy, axis=0) #broadcast 떄 이방식으로 back떄 풀어써줘야 한다.

In [107]:
db

array([5, 7, 9])

---

In [111]:
class Affine :
    def __init__(self, W, b) :
        self.W = W
        self.b = b
        self.x = None
        self.dW = None
        self.db = None

    def forward(self, x) :
        self.x = x
        out = np.dot(x,self.W) + self.b

        return out

    def backward(self, dout) :
        dx = np.dot(dout, self.W.T)
        self.dW = np.dot(self.x.T, dout)
        self.db = np.sum(dout, axis=0)

        return dx

In [112]:
from common.functions import *

In [117]:
class SoftmaxWithLoss :
    def __init__(self) :
        self.loss = None
        self.y = None
        self.t = None

    def forward(self, x, t) :
        self.t = t # x는 데이터, t는 정답
        self.y = softmax(x)
        self.loss = cross_entropy_error(self.y, self.t)

        return self.loss

    def backward(self, dout = 1) :
        batch_size = self.t.shape[0]
        dx = (self.y - self.t) / batch_size

        return dx