In [2]:
docs = ["the cat in the hat", "the cow jumped over the moon", "the cat mooed and the cow meowed",
        "the cat said to the cow cow you are not a cat"]

In [17]:
docs 

['t']
['t']
['t']
['t']


In [10]:
sen.split(' ')

['the',
 'cat',
 'said',
 'to',
 'the',
 'cow',
 'cow',
 'you',
 'are',
 'not',
 'a',
 'cat']

In [22]:
for i in range (3) :
    temp=[]
    word=docs[i].split()
    temp.append(word)

In [23]:
word

['the', 'cat', 'mooed', 'and', 'the', 'cow', 'meowed']

In [24]:
temp

[['the', 'cat', 'mooed', 'and', 'the', 'cow', 'meowed']]

In [25]:
docs[0]

'the cat in the hat'

In [26]:
docs[1]

'the cow jumped over the moon'

In [32]:
len(set(' '.join(docs).split()))

17

In [38]:
vvocabulary = set(' '.join(docs).split())

In [53]:
vvocabulary

{'a',
 'and',
 'are',
 'cat',
 'cow',
 'hat',
 'in',
 'jumped',
 'meowed',
 'mooed',
 'moon',
 'not',
 'over',
 'said',
 'the',
 'to',
 'you'}

In [54]:
common_words=set(['a','to','the','in','and','are'])

In [55]:
vocabulary=vvocabulary - common_words

In [56]:
vocabulary

{'cat',
 'cow',
 'hat',
 'jumped',
 'meowed',
 'mooed',
 'moon',
 'not',
 'over',
 'said',
 'you'}

In [75]:
'cat' in docs[0]

True

In [78]:
for word in docs[0].split() :
    #print(word)
    if word == vocabulary :
        print(True)
    else :
        print(False)

False
False
False
False
False


In [89]:
doc

'cat'

In [88]:
doc.split()

['cat']

In [92]:
docs[0]

'the cat in the hat'

In [94]:
for doc in docs :
    #print(doc)
    dict={}
    for v in vocabulary :
        print(v, v in doc)
        #dict[v]=dict


not False
jumped False
you False
cow False
hat True
over False
said False
moon False
mooed False
cat True
meowed False
not False
jumped True
you False
cow True
hat False
over True
said False
moon True
mooed False
cat False
meowed False
not False
jumped False
you False
cow True
hat False
over False
said False
moon False
mooed True
cat True
meowed True
not True
jumped False
you True
cow True
hat False
over False
said True
moon False
mooed False
cat True
meowed False


In [82]:
doc

'the cat said to the cow cow you are not a cat'

In [70]:
vocabulary - set(docs[0].split())

{'cow', 'jumped', 'meowed', 'mooed', 'moon', 'not', 'over', 'said', 'you'}

In [59]:
{'cat':True, 'hat':True, 'cow':False}

{'cat': True, 'hat': True, 'cow': False}

In [62]:
vocabulary

{'cat',
 'cow',
 'hat',
 'jumped',
 'meowed',
 'mooed',
 'moon',
 'not',
 'over',
 'said',
 'you'}

In [65]:
if docs[0].split() == vocabulary :
    print(True)
else :
    print(False)

False


In [152]:
dic_list=[]
for d in docs :
    dict={}
    for v in vocabulary :
        #print(v, v in d)
        dict[v] = v.count(d)
    dic_list.append(dict)

In [153]:
dic_list

[{'not': 0,
  'jumped': 0,
  'you': 0,
  'cow': 0,
  'hat': 0,
  'over': 0,
  'said': 0,
  'moon': 0,
  'mooed': 0,
  'cat': 0,
  'meowed': 0},
 {'not': 0,
  'jumped': 0,
  'you': 0,
  'cow': 0,
  'hat': 0,
  'over': 0,
  'said': 0,
  'moon': 0,
  'mooed': 0,
  'cat': 0,
  'meowed': 0},
 {'not': 0,
  'jumped': 0,
  'you': 0,
  'cow': 0,
  'hat': 0,
  'over': 0,
  'said': 0,
  'moon': 0,
  'mooed': 0,
  'cat': 0,
  'meowed': 0},
 {'not': 0,
  'jumped': 0,
  'you': 0,
  'cow': 0,
  'hat': 0,
  'over': 0,
  'said': 0,
  'moon': 0,
  'mooed': 0,
  'cat': 0,
  'meowed': 0}]

In [156]:
word_count=[{ v: d.count(v) for v in vocabulary} for d in docs]

In [157]:
wcs = pd.DataFrame(word_count)

In [158]:
wcs.sort_index(axis=1)

cat  cow  hat  jumped  meowed  mooed  moon  not  over  said  you
0    1    0    1       0       0      0     0    0     0     0    0
1    0    1    0       1       0      0     1    0     1     0    0
2    1    1    0       0       1      1     0    0     0     0    0
3    2    2    0       0       0      0     0    1     0     1    1

In [104]:
import pandas as pd

In [111]:
dcs= pd.DataFrame(doc_contains)

In [112]:
dcs

not  jumped    you    cow    hat   over   said   moon  mooed    cat  \
0  False   False  False  False   True  False  False  False  False   True   
1  False    True  False   True  False   True  False   True  False  False   
2  False   False  False   True  False  False  False  False   True   True   
3   True   False   True   True  False  False   True  False  False   True   

   meowed  
0   False  
1   False  
2    True  
3   False

In [113]:
dcs.sort_index(axis=1)

cat    cow    hat  jumped  meowed  mooed   moon    not   over   said  \
0   True  False   True   False   False  False  False  False  False  False   
1  False   True  False    True   False  False   True  False   True  False   
2   True   True  False   False    True   True  False  False  False  False   
3   True   True  False   False   False  False  False   True  False   True   

     you  
0  False  
1  False  
2  False  
3   True

In [139]:
import pandas as pd
import numpy as np

In [151]:
dic_list=[]
for d in docs :
    print(d)
    dict={}
    for v in vocabulary :
        print(v)
        dict[v] = v.count()
    dic_list.append(dict)

the cat in the hat
the cow jumped over the moon
the cat mooed and the cow meowed
the cat said to the cow cow you are not a cat


In [131]:
from sklearn.feature_extraction.text import CountVectorizer #변수가 몇갠지 세어줌.

In [125]:
sparse=CountVectorizer(stop_words='english').fit_transform(docs)

In [126]:
sparse.todense()

matrix([[1, 0, 1, 0, 0, 0, 0, 0],
        [0, 1, 0, 1, 0, 0, 1, 0],
        [1, 1, 0, 0, 1, 1, 0, 0],
        [2, 2, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [159]:
wcs.sort_index(axis=1)

cat  cow  hat  jumped  meowed  mooed  moon  not  over  said  you
0    1    0    1       0       0      0     0    0     0     0    0
1    0    1    0       1       0      0     1    0     1     0    0
2    1    1    0       0       1      1     0    0     0     0    0
3    2    2    0       0       0      0     0    1     0     1    1

In [128]:
sparse.get_shape()

(4, 8)

In [132]:
dcs

not  jumped    you    cow    hat   over   said   moon  mooed    cat  \
0  False   False  False  False   True  False  False  False  False   True   
1  False    True  False   True  False   True  False   True  False  False   
2  False   False  False   True  False  False  False  False   True   True   
3   True   False   True   True  False  False   True  False  False   True   

   meowed  
0   False  
1   False  
2    True  
3   False

In [160]:
doc

not  jumped    you    cow    hat   over   said   moon  mooed    cat  \
0  False   False  False  False   True  False  False  False  False   True   
1  False    True  False   True  False   True  False   True  False  False   
2  False   False  False   True  False  False  False  False   True   True   
3   True   False   True   True  False  False   True  False  False   True   

   meowed  
0   False  
1   False  
2    True  
3   False

In [161]:
docs

['the cat in the hat',
 'the cow jumped over the moon',
 'the cat mooed and the cow meowed',
 'the cat said to the cow cow you are not a cat']

In [164]:
doc_freq = pd.DataFrame(dcs.sum(axis=0)).T

In [165]:
doc_freq

not  jumped  you  cow  hat  over  said  moon  mooed  cat  meowed
0    1       1    1    3    1     1     1     1      1    3       1

In [166]:
import numpy as np

In [167]:
pd.options.display.float_format = '{:.2f}'.format

In [168]:
idf = np.log(len(docs)/ doc_freq)

In [169]:
idf #수치가 작을수록 등장빈도가 높음!!

not  jumped  you  cow  hat  over  said  moon  mooed  cat  meowed
0 1.39    1.39 1.39 0.29 1.39  1.39  1.39  1.39   1.39 0.29    1.39

In [172]:
wcs # 이것이 TF

not  jumped  you  cow  hat  over  said  moon  mooed  cat  meowed
0    0       0    0    0    1     0     0     0      0    1       0
1    0       1    0    1    0     1     0     1      0    0       0
2    0       0    0    1    0     0     0     0      1    1       1
3    1       0    1    2    0     0     1     0      0    2       0

In [173]:
tf_idf = wcs * idf.iloc[0]

In [174]:
tf_idf # 자주 등장하는 단어는 중요도가 낮다.

not  jumped  you  cow  hat  over  said  moon  mooed  cat  meowed
0 0.00    0.00 0.00 0.00 1.39  0.00  0.00  0.00   0.00 0.29    0.00
1 0.00    1.39 0.00 0.29 0.00  1.39  0.00  1.39   0.00 0.00    0.00
2 0.00    0.00 0.00 0.29 0.00  0.00  0.00  0.00   1.39 0.29    1.39
3 1.39    0.00 1.39 0.58 0.00  0.00  1.39  0.00   0.00 0.58    0.00

In [182]:
from sklearn.preprocessing import Normalizer

In [188]:
Normalizer(norm='l1').fit_transform(tf_idf)

array([[0.        , 0.        , 0.        , 0.        , 0.82814449,
        0.        , 0.        , 0.        , 0.        , 0.17185551,
        0.        ],
       [0.        , 0.31176747, 0.        , 0.0646976 , 0.        ,
        0.31176747, 0.        , 0.31176747, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.08592775, 0.        ,
        0.        , 0.        , 0.        , 0.41407225, 0.08592775,
        0.41407225],
       [0.26109149, 0.        , 0.26109149, 0.10836276, 0.        ,
        0.        , 0.26109149, 0.        , 0.        , 0.10836276,
        0.        ]])

In [184]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [203]:
vectorizer=TfidfVectorizer(norm='l1', stop_words='english')

In [204]:
sparse.todense()

matrix([[1, 0, 1, 0, 0, 0, 0, 0],
        [0, 1, 0, 1, 0, 0, 1, 0],
        [1, 1, 0, 0, 1, 1, 0, 0],
        [2, 2, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [205]:
sparse = vectorizer.fit_transform(docs)

In [206]:
vectorizer.get_feature_names_out()

array(['cat', 'cow', 'hat', 'jumped', 'meowed', 'mooed', 'moon', 'said'],
      dtype=object)

In [207]:
sparse.todense()

matrix([[0.38960636, 0.        , 0.61039364, 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.24193237, 0.        , 0.37903381, 0.        ,
         0.        , 0.37903381, 0.        ],
        [0.19480318, 0.19480318, 0.        , 0.        , 0.30519682,
         0.30519682, 0.        , 0.        ],
        [0.35927972, 0.35927972, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.28144056]])

---------------

In [209]:
from sklearn.datasets import fetch_20newsgroups #20개의 뉴스기사 (형식은 email)

In [210]:
twenty_train = fetch_20newsgroups(subset='train', shuffle=True, random_state=0)

In [212]:
len(twenty_train.target_names)

20

In [213]:
from collections import Counter

In [215]:
Counter(twenty_train.target) #각각의 문서의 개수

Counter({15: 599,
         13: 594,
         10: 600,
         12: 591,
         7: 594,
         1: 584,
         5: 593,
         4: 578,
         3: 590,
         17: 564,
         2: 591,
         8: 598,
         16: 546,
         9: 597,
         6: 585,
         11: 595,
         18: 465,
         14: 593,
         0: 480,
         19: 377})

In [224]:
twenty_train.target_names[15]

'soc.religion.christian'

In [219]:
print('\n'.join(twenty_train.data[0].split('\n')))

From: kbanner@philae.sas.upenn.edu (Ken Banner)
Subject: Re: SATANIC TOUNGES
Organization: University of Pennsylvania
Lines: 51

In article <May.5.02.53.10.1993.28880@athos.rutgers.edu> koberg@spot.Colorado.EDU (Allen Koberg) writes:

>.....................................................There is dis-
>crepancy even among charismatic organizations as to the proper use
>of tongues.  Be it revelatory with interpretation, for prayer use,
>or for signifying believers (which I doubt since any one can do it).
>Pentecostals (Assembly of God, Church of Christ), seem to espouse all
>three.  Neo-pentecostals tend to view prayer use and as a sign as the
>uses.  Speaking in tongues during a service is not usually done by
>neo-pentecostals because for the most part, they still attend Protestant
>churches.  Non-denominational churches seem to view the use as a sign
>as merely optional, but recommended.

Koberg,

	Just a couple of minor corrections here...

	1)  The Churches of Christ do not usually 

In [225]:
twenty_test = fetch_20newsgroups(subset='test', shuffle=True, random_state=0)

In [247]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline
from sklearn.metrics import f1_score

In [232]:
pipe = make_pipeline(TfidfVectorizer(), RandomForestClassifier())

In [239]:
pipe.fit(twenty_train.data, twenty_train.target)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('randomforestclassifier', RandomForestClassifier())])

In [241]:
pipe.score(twenty_train.data, twenty_train.target)

0.9999116139296447

In [242]:
pipe.score(twenty_test.data, twenty_test.target)

0.7584970791290494

In [238]:
print('\n'.join(twenty_test.data[0].split('\n')))

From: mliggett@silver.ucs.indiana.edu (matthew liggett)
Subject: Re: V4 V6 V8 V12 Vx?
Nntp-Posting-Host: silver.ucs.indiana.edu
Organization: Indiana University
Lines: 32

In <1993Apr23.132214.6755@cs.tulane.edu> finnegan@nrlssc.navy.mil writes:

>In article <Apr22.202724.24131@engr.washington.edu>
>eliot@stalfos.engr.washington.edu (eliot) writes:
>>
>>the subarus all use 180 degree vees in their engines..  :-)
>>
>>
>>eliot

>Wouldn't that make them an I4?  Or would they 
>really be an _4 (henceforth referred to as
>"underscore 4")?

horizontally opposed 4.
or 'boxer'
great idea, actually..
smooth running; low center of gravity..
also used in some honda gullwings, corvairs, porsches (others?)
...

>Kenneth
>finnegan@nrlssc.navy.mil




-- 
/-=*=-=*=-=*=-=*=-=*=-=*=-=*=-=*=-=*=-=*=-=*=-=*=-=*=-=*=-=*=-=*=-=*=-=*=-=*=-\
| |\/|  __   -=> mliggett@silver.ucs.indiana.edu <=- (mliggett@iugold.bitnet  |
* |  |/\||   'junk' collector, toys R us kid, antiauthoritarian, and fan of   *
| frogs,

In [255]:
y_pred = pipe.predict(twenty_test.data)

In [256]:
f1_score(twenty_test.target, y_pred, average='macro')

0.7453099880665475

In [249]:
from xgboost import XGBClassifier

In [250]:
from sklearn.model_selection import train_test_split

In [258]:
from sklearn.model_selection import GridSearchCV

In [251]:
pipe1 = make_pipeline(TfidfVectorizer(), XGBClassifier())

In [252]:
x_train, x_test, y_train, y_test = train_test_split(twenty_train.data, twenty_train.target, test_size=0.2)

In [253]:
pipe1.fit(x_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('xgbclassifier',
                 XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
                               colsample_bylevel=1, colsample_bynode=1,
                               colsample_bytree=1, early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, gamma=0, gpu_id=-1,
                               grow_policy='depthwise', importance_type=None,
                               interaction_constraints='',
                               learning_rate=0.300000012, max_bin=256,
                               max_cat_threshold=64, max_cat_to_onehot=4,
                               max_delta_step=0, max_depth=6, max_leaves=0,
                               min_child_weight=1, missing=nan,
                               monotone_constraints='()', n_estimators=100,
                               n_j

In [254]:
pipe1.score(x_train,y_train)

0.9998895149707214

In [257]:
pipe1.score(x_test, y_test)

0.8144056562085726

In [259]:
pipe1.get_params().keys()

dict_keys(['memory', 'steps', 'verbose', 'tfidfvectorizer', 'xgbclassifier', 'tfidfvectorizer__analyzer', 'tfidfvectorizer__binary', 'tfidfvectorizer__decode_error', 'tfidfvectorizer__dtype', 'tfidfvectorizer__encoding', 'tfidfvectorizer__input', 'tfidfvectorizer__lowercase', 'tfidfvectorizer__max_df', 'tfidfvectorizer__max_features', 'tfidfvectorizer__min_df', 'tfidfvectorizer__ngram_range', 'tfidfvectorizer__norm', 'tfidfvectorizer__preprocessor', 'tfidfvectorizer__smooth_idf', 'tfidfvectorizer__stop_words', 'tfidfvectorizer__strip_accents', 'tfidfvectorizer__sublinear_tf', 'tfidfvectorizer__token_pattern', 'tfidfvectorizer__tokenizer', 'tfidfvectorizer__use_idf', 'tfidfvectorizer__vocabulary', 'xgbclassifier__objective', 'xgbclassifier__use_label_encoder', 'xgbclassifier__base_score', 'xgbclassifier__booster', 'xgbclassifier__callbacks', 'xgbclassifier__colsample_bylevel', 'xgbclassifier__colsample_bynode', 'xgbclassifier__colsample_bytree', 'xgbclassifier__early_stopping_rounds', '

In [ ]:
param_grid = {}

In [ ]:
mod =GridSearchCV(pipe1, param_grid, n_jobs=-1)

-------------

In [260]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import make_pipeline

In [262]:
pipe=make_pipeline(TfidfVectorizer(), RandomForestClassifier())

In [263]:
pipe.fit(twenty_train.data, twenty_train.target)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('randomforestclassifier', RandomForestClassifier())])

In [264]:
pipe.score(twenty_train.data, twenty_train.target)

0.9999116139296447

In [265]:
pipe.score(twenty_test.data, twenty_test.target)

0.758364312267658

In [266]:
from sklearn.metrics import f1_score

In [267]:
pred= pipe.predict(twenty_test.data)

In [268]:
f1_score(twenty_test.target, pred, average='macro')

0.7442729005274582

In [270]:
from sklearn.model_selection import GridSearchCV

In [275]:
model = RandomForestClassifier()

In [276]:
pipe.named_steps['randomforestclassifier']

RandomForestClassifier()

In [282]:
param_grid ={'randomforestclassifier__criterion' : ['gini','entropy','log_loss'],
             'randomforestclassifier__max_features' : ['sqrt','log2'],
                          'tfidfvectorizer__norm' : ['l1','l2']}

In [283]:
grid_model =GridSearchCV(pipe, param_grid, verbose=1, n_jobs=-1)

In [284]:
grid_model.fit(twenty_train.data, twenty_train.target)

Fitting 5 folds for each of 12 candidates, totalling 60 fits


C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\pipeline.py", line 394, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 450, in fit
    trees = Parallel(
  File "C:\Users\user\anaconda3\lib\site-pa

GridSearchCV(estimator=Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                                       ('randomforestclassifier',
                                        RandomForestClassifier())]),
             n_jobs=-1,
             param_grid={'randomforestclassifier__criterion': ['gini',
                                                               'entropy',
                                                               'log_loss'],
                         'randomforestclassifier__max_features': ['sqrt',
                                                                  'log2'],
                         'tfidfvectorizer__norm': ['l1', 'l2']},
             verbose=1)

In [285]:
grid_model.best_estimator_.score(twenty_test.data, twenty_test.target)

0.7326075411577271