In [1]:
import pandas as pd
import pickle

In [2]:
real_data = pd.read_csv('sonar_csv.csv')

In [3]:
real = real_data.drop('Class', axis=1)

In [4]:
real

attribute_1  attribute_2  attribute_3  attribute_4  attribute_5  \
0         0.0200       0.0371       0.0428       0.0207       0.0954   
1         0.0453       0.0523       0.0843       0.0689       0.1183   
2         0.0262       0.0582       0.1099       0.1083       0.0974   
3         0.0100       0.0171       0.0623       0.0205       0.0205   
4         0.0762       0.0666       0.0481       0.0394       0.0590   
..           ...          ...          ...          ...          ...   
203       0.0187       0.0346       0.0168       0.0177       0.0393   
204       0.0323       0.0101       0.0298       0.0564       0.0760   
205       0.0522       0.0437       0.0180       0.0292       0.0351   
206       0.0303       0.0353       0.0490       0.0608       0.0167   
207       0.0260       0.0363       0.0136       0.0272       0.0214   

     attribute_6  attribute_7  attribute_8  attribute_9  attribute_10  ...  \
0         0.0986       0.1539       0.1601       0.3109        0.2111  ...   
1         0.2583       0.2156       0.3481       0.3337        0.2872  ...   
2         0.2280       0.2431       0.3771       0.5598        0.6194  ...   
3         0.0368       0.1098       0.1276       0.0598        0.1264  ...   
4         0.0649       0.1209       0.2467       0.3564        0.4459  ...   
..           ...          ...          ...          ...           ...  ...   
203       0.1630       0.2028       0.1694       0.2328        0.2684  ...   
204       0.0958       0.0990       0.1018       0.1030        0.2154  ...   
205       0.1171       0.1257       0.1178       0.1258        0.2529  ...   
206       0.1354       0.1465       0.1123       0.1945        0.2354  ...   
207       0.0338       0.0655       0.1400       0.1843        0.2354  ...   

     attribute_51  attribute_52  attribute_53  attribute_54  attribute_55  \
0          0.0232        0.0027        0.0065        0.0159        0.0072   
1          0.0125        0.0084        0.0089        0.0048        0.0094   
2          0.0033        0.0232        0.0166        0.0095        0.0180   
3          0.0241        0.0121        0.0036        0.0150        0.0085   
4          0.0156        0.0031        0.0054        0.0105        0.0110   
..            ...           ...           ...           ...           ...   
203        0.0203        0.0116        0.0098        0.0199        0.0033   
204        0.0051        0.0061        0.0093        0.0135        0.0063   
205        0.0155        0.0160        0.0029        0.0051        0.0062   
206        0.0042        0.0086        0.0046        0.0126        0.0036   
207        0.0181        0.0146        0.0129        0.0047        0.0039   

     attribute_56  attribute_57  attribute_58  attribute_59  attribute_60  
0          0.0167        0.0180        0.0084        0.0090        0.0032  
1          0.0191        0.0140        0.0049        0.0052        0.0044  
2          0.0244        0.0316        0.0164        0.0095        0.0078  
3          0.0073        0.0050        0.0044        0.0040        0.0117  
4          0.0015        0.0072        0.0048        0.0107        0.0094  
..            ...           ...           ...           ...           ...  
203        0.0101        0.0065        0.0115        0.0193        0.0157  
204        0.0063        0.0034        0.0032        0.0062        0.0067  
205        0.0089        0.0140        0.0138        0.0077        0.0031  
206        0.0035        0.0034        0.0079        0.0036        0.0048  
207        0.0061        0.0040        0.0036        0.0061        0.0115  

[208 rows x 60 columns]

In [6]:
real.iloc[100].values

array([0.0629, 0.1065, 0.1526, 0.1229, 0.1437, 0.119 , 0.0884, 0.0907,
       0.2107, 0.3597, 0.5466, 0.5205, 0.5127, 0.5395, 0.6558, 0.8705,
       0.9786, 0.9335, 0.7917, 0.7383, 0.6908, 0.385 , 0.0671, 0.0502,
       0.2717, 0.2839, 0.2234, 0.1911, 0.0408, 0.2531, 0.1979, 0.1891,
       0.2433, 0.1956, 0.2667, 0.134 , 0.1073, 0.2023, 0.1794, 0.0227,
       0.1313, 0.1775, 0.1549, 0.1626, 0.0708, 0.0129, 0.0795, 0.0762,
       0.0117, 0.0061, 0.0257, 0.0089, 0.0262, 0.0108, 0.0138, 0.0187,
       0.023 , 0.0057, 0.0113, 0.0131])

In [39]:
real_data2=real.iloc[100].values.reshape(1, -1) #reshape은 재구조화!!

In [40]:
real_data2

array([[0.0629, 0.1065, 0.1526, 0.1229, 0.1437, 0.119 , 0.0884, 0.0907,
        0.2107, 0.3597, 0.5466, 0.5205, 0.5127, 0.5395, 0.6558, 0.8705,
        0.9786, 0.9335, 0.7917, 0.7383, 0.6908, 0.385 , 0.0671, 0.0502,
        0.2717, 0.2839, 0.2234, 0.1911, 0.0408, 0.2531, 0.1979, 0.1891,
        0.2433, 0.1956, 0.2667, 0.134 , 0.1073, 0.2023, 0.1794, 0.0227,
        0.1313, 0.1775, 0.1549, 0.1626, 0.0708, 0.0129, 0.0795, 0.0762,
        0.0117, 0.0061, 0.0257, 0.0089, 0.0262, 0.0108, 0.0138, 0.0187,
        0.023 , 0.0057, 0.0113, 0.0131]])

In [28]:
with open('scaler.pkl', 'rb') as f :
    scal = pickle.load(f)

In [9]:
real_pre=scal.transform(real_data2)

In [10]:
real_pre

array([[0.0629, 0.1065, 0.1526, 0.1229, 0.1437, 0.119 , 0.0884, 0.0907,
        0.2107, 0.3597, 0.5466, 0.5205, 0.5127, 0.5395, 0.6558, 0.8705,
        0.9786, 0.9335, 0.7917, 0.7383, 0.6908, 0.385 , 0.0671, 0.0502,
        0.2717, 0.2839, 0.2234, 0.1911, 0.0408, 0.2531, 0.1979, 0.1891,
        0.2433, 0.1956, 0.2667, 0.134 , 0.1073, 0.2023, 0.1794, 0.0227,
        0.1313, 0.1775, 0.1549, 0.1626, 0.0708, 0.0129, 0.0795, 0.0762,
        0.0117, 0.0061, 0.0257, 0.0089, 0.0262, 0.0108, 0.0138, 0.0187,
        0.023 , 0.0057, 0.0113, 0.0131]])

In [11]:
with open('model.pkl', 'rb') as f :
    model1 = pickle.load(f)

In [13]:
model1.predict(real_pre)[0]

'Mine'