In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [2]:
sonar = pd.read_csv('sonar_csv.csv')

In [3]:
sonar

attribute_1  attribute_2  attribute_3  attribute_4  attribute_5  \
0         0.0200       0.0371       0.0428       0.0207       0.0954   
1         0.0453       0.0523       0.0843       0.0689       0.1183   
2         0.0262       0.0582       0.1099       0.1083       0.0974   
3         0.0100       0.0171       0.0623       0.0205       0.0205   
4         0.0762       0.0666       0.0481       0.0394       0.0590   
..           ...          ...          ...          ...          ...   
203       0.0187       0.0346       0.0168       0.0177       0.0393   
204       0.0323       0.0101       0.0298       0.0564       0.0760   
205       0.0522       0.0437       0.0180       0.0292       0.0351   
206       0.0303       0.0353       0.0490       0.0608       0.0167   
207       0.0260       0.0363       0.0136       0.0272       0.0214   

     attribute_6  attribute_7  attribute_8  attribute_9  attribute_10  ...  \
0         0.0986       0.1539       0.1601       0.3109        0.2111  ...   
1         0.2583       0.2156       0.3481       0.3337        0.2872  ...   
2         0.2280       0.2431       0.3771       0.5598        0.6194  ...   
3         0.0368       0.1098       0.1276       0.0598        0.1264  ...   
4         0.0649       0.1209       0.2467       0.3564        0.4459  ...   
..           ...          ...          ...          ...           ...  ...   
203       0.1630       0.2028       0.1694       0.2328        0.2684  ...   
204       0.0958       0.0990       0.1018       0.1030        0.2154  ...   
205       0.1171       0.1257       0.1178       0.1258        0.2529  ...   
206       0.1354       0.1465       0.1123       0.1945        0.2354  ...   
207       0.0338       0.0655       0.1400       0.1843        0.2354  ...   

     attribute_52  attribute_53  attribute_54  attribute_55  attribute_56  \
0          0.0027        0.0065        0.0159        0.0072        0.0167   
1          0.0084        0.0089        0.0048        0.0094        0.0191   
2          0.0232        0.0166        0.0095        0.0180        0.0244   
3          0.0121        0.0036        0.0150        0.0085        0.0073   
4          0.0031        0.0054        0.0105        0.0110        0.0015   
..            ...           ...           ...           ...           ...   
203        0.0116        0.0098        0.0199        0.0033        0.0101   
204        0.0061        0.0093        0.0135        0.0063        0.0063   
205        0.0160        0.0029        0.0051        0.0062        0.0089   
206        0.0086        0.0046        0.0126        0.0036        0.0035   
207        0.0146        0.0129        0.0047        0.0039        0.0061   

     attribute_57  attribute_58  attribute_59  attribute_60  Class  
0          0.0180        0.0084        0.0090        0.0032   Rock  
1          0.0140        0.0049        0.0052        0.0044   Rock  
2          0.0316        0.0164        0.0095        0.0078   Rock  
3          0.0050        0.0044        0.0040        0.0117   Rock  
4          0.0072        0.0048        0.0107        0.0094   Rock  
..            ...           ...           ...           ...    ...  
203        0.0065        0.0115        0.0193        0.0157   Mine  
204        0.0034        0.0032        0.0062        0.0067   Mine  
205        0.0140        0.0138        0.0077        0.0031   Mine  
206        0.0034        0.0079        0.0036        0.0048   Mine  
207        0.0040        0.0036        0.0061        0.0115   Mine  

[208 rows x 61 columns]

In [4]:
sonar['Class'].value_counts()

Mine    111
Rock     97
Name: Class, dtype: int64

In [5]:
sonar['Class'].unique()

array(['Rock', 'Mine'], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
col_list = ['Class']
for col in col_list : 
    label = LabelEncoder()
    label.fit(sonar[col].unique())
    sonar[col] = label.transform(sonar[col])

In [8]:
sonar

attribute_1  attribute_2  attribute_3  attribute_4  attribute_5  \
0         0.0200       0.0371       0.0428       0.0207       0.0954   
1         0.0453       0.0523       0.0843       0.0689       0.1183   
2         0.0262       0.0582       0.1099       0.1083       0.0974   
3         0.0100       0.0171       0.0623       0.0205       0.0205   
4         0.0762       0.0666       0.0481       0.0394       0.0590   
..           ...          ...          ...          ...          ...   
203       0.0187       0.0346       0.0168       0.0177       0.0393   
204       0.0323       0.0101       0.0298       0.0564       0.0760   
205       0.0522       0.0437       0.0180       0.0292       0.0351   
206       0.0303       0.0353       0.0490       0.0608       0.0167   
207       0.0260       0.0363       0.0136       0.0272       0.0214   

     attribute_6  attribute_7  attribute_8  attribute_9  attribute_10  ...  \
0         0.0986       0.1539       0.1601       0.3109        0.2111  ...   
1         0.2583       0.2156       0.3481       0.3337        0.2872  ...   
2         0.2280       0.2431       0.3771       0.5598        0.6194  ...   
3         0.0368       0.1098       0.1276       0.0598        0.1264  ...   
4         0.0649       0.1209       0.2467       0.3564        0.4459  ...   
..           ...          ...          ...          ...           ...  ...   
203       0.1630       0.2028       0.1694       0.2328        0.2684  ...   
204       0.0958       0.0990       0.1018       0.1030        0.2154  ...   
205       0.1171       0.1257       0.1178       0.1258        0.2529  ...   
206       0.1354       0.1465       0.1123       0.1945        0.2354  ...   
207       0.0338       0.0655       0.1400       0.1843        0.2354  ...   

     attribute_52  attribute_53  attribute_54  attribute_55  attribute_56  \
0          0.0027        0.0065        0.0159        0.0072        0.0167   
1          0.0084        0.0089        0.0048        0.0094        0.0191   
2          0.0232        0.0166        0.0095        0.0180        0.0244   
3          0.0121        0.0036        0.0150        0.0085        0.0073   
4          0.0031        0.0054        0.0105        0.0110        0.0015   
..            ...           ...           ...           ...           ...   
203        0.0116        0.0098        0.0199        0.0033        0.0101   
204        0.0061        0.0093        0.0135        0.0063        0.0063   
205        0.0160        0.0029        0.0051        0.0062        0.0089   
206        0.0086        0.0046        0.0126        0.0036        0.0035   
207        0.0146        0.0129        0.0047        0.0039        0.0061   

     attribute_57  attribute_58  attribute_59  attribute_60  Class  
0          0.0180        0.0084        0.0090        0.0032      1  
1          0.0140        0.0049        0.0052        0.0044      1  
2          0.0316        0.0164        0.0095        0.0078      1  
3          0.0050        0.0044        0.0040        0.0117      1  
4          0.0072        0.0048        0.0107        0.0094      1  
..            ...           ...           ...           ...    ...  
203        0.0065        0.0115        0.0193        0.0157      0  
204        0.0034        0.0032        0.0062        0.0067      0  
205        0.0140        0.0138        0.0077        0.0031      0  
206        0.0034        0.0079        0.0036        0.0048      0  
207        0.0040        0.0036        0.0061        0.0115      0  

[208 rows x 61 columns]

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

In [10]:
model = LogisticRegression()

In [11]:
x = sonar.drop(['Class'],axis=1)

In [12]:
y= sonar['Class']

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1, random_state=0, stratify=y)

In [14]:
model.fit(x_train, y_train)

LogisticRegression()

In [64]:
x_train

array([[ 0.43842592, -0.82597191, -0.43050828, ..., -0.55677057,
        -0.90845389, -0.99275199],
       [ 0.70074558,  0.41166228,  1.04312784, ..., -0.48133505,
        -0.43934248, -0.40089879],
       [ 0.35671979, -0.31004247, -0.52005214, ..., -0.40589954,
         0.07668006, -0.08524374],
       ...,
       [ 0.3782214 , -0.19969919, -0.0313985 , ..., -0.28520272,
        -0.5800759 , -0.22334282],
       [-0.7355621 ,  0.58761509,  0.48028071, ..., -0.11924459,
        -0.78335751,  1.4535746 ],
       [ 3.4314503 ,  2.66326183,  1.25547471, ...,  1.87225297,
         1.53092542,  2.42026817]])

In [15]:
pre_train = model.predict(x_train)

In [16]:
mean_absolute_error(pre_train, y_train)

0.1711229946524064

In [17]:
model.score(x_train, y_train)

0.8288770053475936

In [18]:
pre_test = model.predict(x_test)

In [19]:
mean_absolute_error(pre_test, y_test)

0.19047619047619047

In [20]:
model.score(x_test, y_test)

0.8095238095238095

In [21]:
model2 = LogisticRegression(max_iter=1000)

In [22]:
model2.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [23]:
model2.score(x_train, y_train)

0.8288770053475936

In [24]:
model2.score(x_test, y_test)

0.8095238095238095

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
scaler = StandardScaler()

In [27]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [28]:
model.fit(x_train, y_train)

LogisticRegression()

In [29]:
model.score(x_train, y_train)

0.93048128342246

In [30]:
model.score(x_test, y_test)

0.8095238095238095

In [31]:
model2.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [32]:
model2.score(x_train, y_train)

0.93048128342246

In [33]:
model2.score(x_test, y_test)

0.8095238095238095

In [34]:
sonar.describe()

attribute_1  attribute_2  attribute_3  attribute_4  attribute_5  \
count   208.000000   208.000000   208.000000   208.000000   208.000000   
mean      0.029164     0.038437     0.043832     0.053892     0.075202   
std       0.022991     0.032960     0.038428     0.046528     0.055552   
min       0.001500     0.000600     0.001500     0.005800     0.006700   
25%       0.013350     0.016450     0.018950     0.024375     0.038050   
50%       0.022800     0.030800     0.034300     0.044050     0.062500   
75%       0.035550     0.047950     0.057950     0.064500     0.100275   
max       0.137100     0.233900     0.305900     0.426400     0.401000   

       attribute_6  attribute_7  attribute_8  attribute_9  attribute_10  ...  \
count   208.000000   208.000000   208.000000   208.000000    208.000000  ...   
mean      0.104570     0.121747     0.134799     0.178003      0.208259  ...   
std       0.059105     0.061788     0.085152     0.118387      0.134416  ...   
min       0.010200     0.003300     0.005500     0.007500      0.011300  ...   
25%       0.067025     0.080900     0.080425     0.097025      0.111275  ...   
50%       0.092150     0.106950     0.112100     0.152250      0.182400  ...   
75%       0.134125     0.154000     0.169600     0.233425      0.268700  ...   
max       0.382300     0.372900     0.459000     0.682800      0.710600  ...   

       attribute_52  attribute_53  attribute_54  attribute_55  attribute_56  \
count    208.000000    208.000000    208.000000    208.000000    208.000000   
mean       0.013420      0.010709      0.010941      0.009290      0.008222   
std        0.009634      0.007060      0.007301      0.007088      0.005736   
min        0.000800      0.000500      0.001000      0.000600      0.000400   
25%        0.007275      0.005075      0.005375      0.004150      0.004400   
50%        0.011400      0.009550      0.009300      0.007500      0.006850   
75%        0.016725      0.014900      0.014500      0.012100      0.010575   
max        0.070900      0.039000      0.035200      0.044700      0.039400   

       attribute_57  attribute_58  attribute_59  attribute_60       Class  
count    208.000000    208.000000    208.000000    208.000000  208.000000  
mean       0.007820      0.007949      0.007941      0.006507    0.466346  
std        0.005785      0.006470      0.006181      0.005031    0.500070  
min        0.000300      0.000300      0.000100      0.000600    0.000000  
25%        0.003700      0.003600      0.003675      0.003100    0.000000  
50%        0.005950      0.005800      0.006400      0.005300    0.000000  
75%        0.010425      0.010350      0.010325      0.008525    1.000000  
max        0.035500      0.044000      0.036400      0.043900    1.000000  

[8 rows x 61 columns]

In [35]:
from sklearn.linear_model import LogisticRegressionCV #한정적 데이터를 효율적으로 사용하기 위해 

In [36]:
sonar.shape

(208, 61)

In [37]:
model2 = LogisticRegressionCV(max_iter=1000) #cv가 등분을 의미  

In [38]:
model2.fit(x_train, y_train)

LogisticRegressionCV(max_iter=1000)

In [39]:
model2.score(x_train, y_train)

0.8663101604278075

In [40]:
model2.score(x_test, y_test)

0.9523809523809523

In [66]:
type(x_train[0])

numpy.ndarray

In [69]:
x_train.reshape(1,-1)

array([[ 0.43842592, -0.82597191, -0.43050828, ...,  1.87225297,
         1.53092542,  2.42026817]])

In [70]:
x_train

array([[ 0.43842592, -0.82597191, -0.43050828, ..., -0.55677057,
        -0.90845389, -0.99275199],
       [ 0.70074558,  0.41166228,  1.04312784, ..., -0.48133505,
        -0.43934248, -0.40089879],
       [ 0.35671979, -0.31004247, -0.52005214, ..., -0.40589954,
         0.07668006, -0.08524374],
       ...,
       [ 0.3782214 , -0.19969919, -0.0313985 , ..., -0.28520272,
        -0.5800759 , -0.22334282],
       [-0.7355621 ,  0.58761509,  0.48028071, ..., -0.11924459,
        -0.78335751,  1.4535746 ],
       [ 3.4314503 ,  2.66326183,  1.25547471, ...,  1.87225297,
         1.53092542,  2.42026817]])

In [73]:
sensor = x_train[0].reshape(1, -1)

In [74]:
print(model2.predict(sensor) , ' 이 탐지되었습니다')

[0]  이 탐지되었습니다


In [75]:
model2.predict(sensor)

array([0])

In [46]:
pip search sklearn

Note: you may need to restart the kernel to use updated packages.


ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.


In [47]:
sonar.describe()

attribute_1  attribute_2  attribute_3  attribute_4  attribute_5  \
count   208.000000   208.000000   208.000000   208.000000   208.000000   
mean      0.029164     0.038437     0.043832     0.053892     0.075202   
std       0.022991     0.032960     0.038428     0.046528     0.055552   
min       0.001500     0.000600     0.001500     0.005800     0.006700   
25%       0.013350     0.016450     0.018950     0.024375     0.038050   
50%       0.022800     0.030800     0.034300     0.044050     0.062500   
75%       0.035550     0.047950     0.057950     0.064500     0.100275   
max       0.137100     0.233900     0.305900     0.426400     0.401000   

       attribute_6  attribute_7  attribute_8  attribute_9  attribute_10  ...  \
count   208.000000   208.000000   208.000000   208.000000    208.000000  ...   
mean      0.104570     0.121747     0.134799     0.178003      0.208259  ...   
std       0.059105     0.061788     0.085152     0.118387      0.134416  ...   
min       0.010200     0.003300     0.005500     0.007500      0.011300  ...   
25%       0.067025     0.080900     0.080425     0.097025      0.111275  ...   
50%       0.092150     0.106950     0.112100     0.152250      0.182400  ...   
75%       0.134125     0.154000     0.169600     0.233425      0.268700  ...   
max       0.382300     0.372900     0.459000     0.682800      0.710600  ...   

       attribute_52  attribute_53  attribute_54  attribute_55  attribute_56  \
count    208.000000    208.000000    208.000000    208.000000    208.000000   
mean       0.013420      0.010709      0.010941      0.009290      0.008222   
std        0.009634      0.007060      0.007301      0.007088      0.005736   
min        0.000800      0.000500      0.001000      0.000600      0.000400   
25%        0.007275      0.005075      0.005375      0.004150      0.004400   
50%        0.011400      0.009550      0.009300      0.007500      0.006850   
75%        0.016725      0.014900      0.014500      0.012100      0.010575   
max        0.070900      0.039000      0.035200      0.044700      0.039400   

       attribute_57  attribute_58  attribute_59  attribute_60       Class  
count    208.000000    208.000000    208.000000    208.000000  208.000000  
mean       0.007820      0.007949      0.007941      0.006507    0.466346  
std        0.005785      0.006470      0.006181      0.005031    0.500070  
min        0.000300      0.000300      0.000100      0.000600    0.000000  
25%        0.003700      0.003600      0.003675      0.003100    0.000000  
50%        0.005950      0.005800      0.006400      0.005300    0.000000  
75%        0.010425      0.010350      0.010325      0.008525    1.000000  
max        0.035500      0.044000      0.036400      0.043900    1.000000  

[8 rows x 61 columns]

In [48]:
for c in sonar.drop('Class', axis=1).columns : 
    print(sonar[c].mean())
    print(sonar[c].median())
    print('-----------')

0.029163942307692307
0.0228
-----------
0.03843653846153848
0.0308
-----------
0.04383221153846154
0.0343
-----------
0.05389230769230771
0.04405
-----------
0.07520240384615384
0.0625
-----------
0.10457019230769235
0.09215000000000001
-----------
0.1217466346153847
0.10694999999999999
-----------
0.13479903846153843
0.1121
-----------
0.17800288461538455
0.15225
-----------
0.2082591346153846
0.1824
-----------
0.2360129807692308
0.2248
-----------
0.25022115384615395
0.24905
-----------
0.2733052884615385
0.26395
-----------
0.2965682692307692
0.2811
-----------
0.32020144230769243
0.28169999999999995
-----------
0.3784865384615385
0.30469999999999997
-----------
0.4159831730769229
0.3084
-----------
0.4523182692307695
0.3683
-----------
0.5048115384615385
0.43495
-----------
0.5630466346153848
0.5425
-----------
0.609060096153846
0.6176999999999999
-----------
0.6242750000000001
0.6649
-----------
0.6469750000000002
0.6997
-----------
0.6726543269230771
0.6985
-----------
0.6754235

In [49]:
from sklearn.preprocessing import StandardScaler

In [50]:
import pickle

In [51]:
with open('scaler.pkl', 'wb') as f :
    pickle.dump(scaler, f)

In [52]:
with open('model.pkl', 'wb') as f :
    pickle.dump(model, f)

In [53]:
model = LogisticRegression()

In [54]:
scaler = StandardScaler()

In [55]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [56]:
model.fit(x_train, y_train)

LogisticRegression()

In [57]:
model.score(x_train, y_train)

0.93048128342246

In [58]:
model.score(x_test, y_test)

0.8095238095238095

In [59]:
print(x_train.shape, y_train.shape)

(187, 60) (187,)


In [60]:
real = x.iloc[0].values.reshape(1, -1) #실제 데이터

In [61]:
real

array([[0.02  , 0.0371, 0.0428, 0.0207, 0.0954, 0.0986, 0.1539, 0.1601,
        0.3109, 0.2111, 0.1609, 0.1582, 0.2238, 0.0645, 0.066 , 0.2273,
        0.31  , 0.2999, 0.5078, 0.4797, 0.5783, 0.5071, 0.4328, 0.555 ,
        0.6711, 0.6415, 0.7104, 0.808 , 0.6791, 0.3857, 0.1307, 0.2604,
        0.5121, 0.7547, 0.8537, 0.8507, 0.6692, 0.6097, 0.4943, 0.2744,
        0.051 , 0.2834, 0.2825, 0.4256, 0.2641, 0.1386, 0.1051, 0.1343,
        0.0383, 0.0324, 0.0232, 0.0027, 0.0065, 0.0159, 0.0072, 0.0167,
        0.018 , 0.0084, 0.009 , 0.0032]])

In [62]:
real = scaler.transform(real)

In [63]:
model.predict(real)[0]

0